// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"url-shortener/config"
	"url-shortener/internal/shortener/application"
	"url-shortener/internal/shortener/infrastructure"
	"url-shortener/internal/shortener/infrastructure/handlers"
	"url-shortener/internal/shortener/infrastructure/repositories"
)

// Injectors from wire.go:

func InitializeServer() *handlers.Handlers {
	idGenerator := infrastructure.NewUUIDGenerator()
	dbConfig := config.NewDBConfig()
	db := infrastructure.NewDB(dbConfig)
	shortenedURLRepository := repositories.NewMySQLShortenedURLRepository(db)
	storeShortenedURL := application.NewStoreShortenedURL(idGenerator, shortenedURLRepository)
	postShortenedURLHandler := handlers.NewPostShortenedURLHandler(storeShortenedURL)
	getShortenedURLS := application.NewGetShortenedURLS(shortenedURLRepository)
	getShortenedURLSHandler := handlers.NewGetShortenedURLSHandler(getShortenedURLS)
	getShortenedURLByCode := application.NewGetShortenedURLByCode(shortenedURLRepository)
	getShortenedURLHandler := handlers.NewGetShortenedURLHandler(getShortenedURLByCode)
	handlersHandlers := handlers.NewHandlers(postShortenedURLHandler, getShortenedURLSHandler, getShortenedURLHandler)
	return handlersHandlers
}
